#!/usr/bin/env bash
cleanup() {
    tput cnorm
    tput rmcup
}
tput smcup
tput civis
trap cleanup EXIT
clear
tput setab 16
thing=$(( $(tput lines) * $(tput cols) ))
printf '%*s' "$thing" ''
while :; do
    sleep 1
done
